#theme: ''
title: "The Ohio Alliance Blog"
baseurl: "https://competent-wright-033824.netlify.app"
#relativeurls: true #ani
#uglyurls: false #ani
copyright: '@TheAlliance'
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
summaryLength: 30
paginate: 10
enableEmoji: yes
enableRobotsTXT: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
#  - _files$
  - _cache$
  - \.knit\.md
  - \.utf8\.md$
permalinks:
  authors: /author/:slug/
  categories: /category/:slug/
  publication_types: /publication-type/:slug/
  tags: /tag/:slug/
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes: webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
  tableOfContents:
    endLevel: 3
    startLevel: 2
imaging:
  anchor: smart
  quality: 90
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
    - name: authors
      weight: 20
  threshold: 80
  toLower: yes
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
# ani
#[blackfriday]
#  hrefTargetBlank: true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
#	angledQuotes: false
#	latexDashes: true
#  extensions: ["backslashLineBreak"]


